# Introduction to Numpy and Pandas

## Introduction to Numpy

Numpy, which stands for numerical Python, is a Python library package to support numerical computations. The basic data structure in numpy is a multi-dimensional array object called ndarray. Numpy provides a suite of functions that can efficiently manipulate elements of the ndarray.

In [4]:
# Import the library

import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

### Creating ndarray

In [6]:
arr1 = np.array([1,2,3,4,5])

In [7]:
list1 = [1,2,3,4,5]
arr2 = np.array(list1)

In [8]:
arr2

array([1, 2, 3, 4, 5])

In [9]:
list2 = [1,2,3, 'Sam', True]
arr3 = np.array(list2)
arr3
# Notice everything for converted to String

array(['1', '2', '3', 'Sam', 'True'], dtype='<U11')

In [10]:
arr4 = np.array([1, 2, 3.8, 4.66, 5])
arr4
# Notice everything for converted to Float

array([1.  , 2.  , 3.8 , 4.66, 5.  ])

In [11]:
arr = np.array(["john", 'Sarah'])
arr

array(['john', 'Sarah'], dtype='<U5')

In [12]:
arr5 = np.array([1,2,3,4,True, False])
arr5
# Notice everything for converted to Integer

array([1, 2, 3, 4, 1, 0])

In [16]:
oneDim = np.array([1.0,2,3,4,5])   # a 1-dimensional array (vector)
print(oneDim)
print("Dimensions = ", oneDim.ndim)
print("Shape = ", oneDim.shape)
print("Size = ", oneDim.size)
print("Array type = ", oneDim.dtype)

[1. 2. 3. 4. 5.]
Dimensions =  1
Shape =  (5,)
Size =  5
Array type =  float64


### Multiple dimension

In [18]:
twoDim = np.array([[1,2],[3,4],[5,6],[7,8]])  # a two-dimensional array (matrix)
print(twoDim)
print("Dimensions = ", twoDim.ndim)
print("Shape = ", twoDim.shape)
print("Size = ", twoDim.size)
print("Array type = ", twoDim.dtype)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Dimensions =  2
Shape =  (4, 2)
Size =  8
Array type =  int32


In [20]:
arrFromTuple = np.array([(1,'a',3.0),(2,'b',3.5)])  # create ndarray from tuple

print(arrFromTuple)
print("Dimensions = ", arrFromTuple.ndim)
print("Shape = ", arrFromTuple.shape)
print("Size = ", arrFromTuple.size)
print("Array type = ", arrFromTuple.dtype)

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
Dimensions =  2
Shape =  (2, 3)
Size =  6
Array type =  <U11


### Random Generate

In [35]:
print('Array of random numbers from a uniform distribution')
print(np.random.rand(5))      # random numbers from a uniform distribution between [0,1]

print('\nArray of integers between -10 and 10, with step size of 2')
print(np.arange(-10, 11, 2))    # similar to range, but returns ndarray instead of list

print('\n2-dimensional array of integers from 0 to 11')
print(np.arange(12).reshape(3,4) )  # reshape to a matrix

Array of random numbers from a uniform distribution
[0.21701827 0.0227949  0.37440027 0.13059573 0.40149733]

Array of integers between -10 and 10, with step size of 2
[-10  -8  -6  -4  -2   0   2   4   6   8  10]

2-dimensional array of integers from 0 to 11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
print('A 2 x 3 matrix of zeros')
print(np.zeros((2,3)))        # a matrix of zeros

print('\nA 3 x 2 matrix of ones')
print(np.ones((3,2)))         # a matrix of ones

print('\nA 3 x 3 identity matrix')
print(np.eye(3))              # a 3 x 3 identity matrix


A 2 x 3 matrix of zeros
[[0. 0. 0.]
 [0. 0. 0.]]

A 3 x 2 matrix of ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]

A 3 x 3 identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Indexing and Slicing

In [42]:
x = np.arange(-5,5)
print('Before: x =', x)

y = x[3:5]            # y is a slice, i.e., pointer to a subarray in x
print('        y =', y)

y[:] = 1000           # modifying the value of y will change x
print('After : y =', y)
print('        x =', x, '\n')

z = x[3:5].copy()     # makes a copy of the subarray
print('Before: x =', x)
print('        z =', z)
z[:] = 500
                       # modifying the value of z will not affect x
print('After : z =', z)
print('        x =', x)

Before: x = [-5 -4 -3 -2 -1  0  1  2  3  4]
        y = [-2 -1]
After : y = [1000 1000]
        x = [  -5   -4   -3 1000 1000    0    1    2    3    4] 

Before: x = [  -5   -4   -3 1000 1000    0    1    2    3    4]
        z = [1000 1000]
After : z = [500 500]
        x = [  -5   -4   -3 1000 1000    0    1    2    3    4]


In [55]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]  # a 2-dim list
print(my2dlist)
print('my2dlist[2] = ', my2dlist[2])          # access the third sublist
print('my2dlist[:][2]', my2dlist[:][2])          # can't access third element of each sublis
# print('my2dlist[:,2]', my2dlist[:,2])          # invalid way to access sublist, will cause syntax error

my2darr = np.array(my2dlist)
print('\nmy2darr =\n', my2darr)

print('my2darr[2] = ', my2darr[2])          # access the third row
print('my2darr[2][:] = ', my2darr[2][:])    # access the third row
print('my2darr[2,:] = ', my2darr[2,:])      # access the third row (similar to 2d list)
print('my2darr[:,2] = ', my2darr[:,2])      # access the third column
print('my2darr[0:2, 2:4] = \n', my2darr[0:2, 2:4])      # access the first two rows & last two columns

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
my2dlist[2] =  [9, 10, 11, 12]
my2dlist[:][2] [9, 10, 11, 12]

my2darr =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
my2darr[2] =  [ 9 10 11 12]
my2darr[2][:] =  [ 9 10 11 12]
my2darr[2,:] =  [ 9 10 11 12]
my2darr[:,2] =  [ 3  7 11]
my2darr[0:2,2:4] = 
 [[3 4]
 [7 8]]


### Numpy Arithmetic and Statistical Functions

In [63]:
x = np.array([1,2,3,4,5])
print('x =', x)

print('x + 1 =', x + 1) # addition
print('x - 1 =', x - 1) # subtraction
print('x * 6 =', x * 6) # multiplication
print('x / 2 =', x / 2) # regular division
print('x // 2 =', x // 2) # integer division
print('x **2 =', x **2) # square
print('x % 2 =', x % 2) # modulus  
print('1 / x =', 1 / x) # division

x = [1 2 3 4 5]
x + 1 = [2 3 4 5 6]
x - 1 = [0 1 2 3 4]
x * 6 = [ 6 12 18 24 30]
x / 2 = [0.5 1.  1.5 2.  2.5]
x // 2 = [0 1 1 2 2]
x **2 = [ 1  4  9 16 25]
x % 2 = [1 0 1 0 1]
1 / x = [1.         0.5        0.33333333 0.25       0.2       ]


In [67]:
x = np.array([2,4,6,8,10])
y = np.array([1,2,3,4,5])
print('x =', x)
print('y =', y)

print('x + y =', x + y) # element-wise addition
print('x - y =', x - y) # element-wise subtraction
print('x * y =', x * y) # element-wise multiplication 
print('x / y =', x / y) # element-wise division
print('x // y =', x // y) # element-wise integer division 
print('x ** y =', x ** y) # element-wise exponentiation

x = [ 2  4  6  8 10]
y = [1 2 3 4 5]
x + y = [ 3  6  9 12 15]
x - y = [1 2 3 4 5]
x * y = [ 2  8 18 32 50]
x / y = [2. 2. 2. 2. 2.]
x // y = [2 2 2 2 2]
x ** y = [     2     16    216   4096 100000]


In [73]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])    
print('y =', y, '\n')

print('np.abs(y) = ', np.abs(y))              # convert to absolute values
print('np.sqrt(abs(y)) = ', np.sqrt(abs(y)))  # apply square root to each element
print('np.sign(y) = ', np.sign(y))            # get the sign of each element
print('np.exp(y) = ', np.exp(y))              # apply exponentiation e^y
print('np.sort(y) = ', np.sort(y))            # sort array

y = [-1.4  0.4 -3.2  2.5  3.4] 

np.abs(y) =  [1.4 0.4 3.2 2.5 3.4]
np.sqrt(abs(y)) =  [1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
np.sign(y) =  [-1.  1. -1.  1.  1.]
np.exp(y) =  [ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
np.sort(y) =  [-3.2 -1.4  0.4  2.5  3.4]


In [78]:
x = np.arange(-2,3)
y = np.random.randn(5)
print('x =', x)
print('y =', y, '\n')

print(np.add(x,y))       # element-wise addition       x + y
print(np.subtract(x,y))  # element-wise subtraction    x - y
print(np.multiply(x,y))  # element-wise multiplication x * y
print(np.divide(x,y))    # element-wise division       x / y
print(np.maximum(x,y))   # element-wise maximum        max(x,y)

x = [-2 -1  0  1  2]
y = [-1.17140329  1.28805679 -2.13176413  1.01776968  0.82638876] 

[-3.17140329  0.28805679 -2.13176413  2.01776968  2.82638876]
[-0.82859671 -2.28805679  2.13176413 -0.01776968  1.17361124]
[ 2.34280658 -1.28805679 -0.          1.01776968  1.65277753]
[ 1.70735392 -0.77636329 -0.          0.98254057  2.42016844]
[-1.17140329  1.28805679  0.          1.01776968  2.        ]


In [88]:
y = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])    
print('y =', y, '\n')

print(np.min(y)) # min 
print(np.max(y)) # max 
print(np.mean(y)) # mean/average
print(np.std(y)) # standard deviation
print(np.sum(y)) # sum 

print(round(np.mean(y), 2))

y = [-3.2 -1.4  0.4  2.5  3.4] 

-3.2
3.4
0.34000000000000014
2.432776191925595
1.7000000000000006
0.34


In [93]:
my2darr = np.arange(1,13,1).reshape(3,4)
print('my2darr =\n', my2darr)

# returns all the elements divisible by 3 in an ndarray
print(my2darr[my2darr % 3 == 0])

# returns elements in the last row divisible by 3
print(my2darr[2, my2darr[2,] % 3 == 0])

my2darr =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  6  9 12]
[ 9 12]


## Introduction to Pandas

Pandas provide two convenient data structures for storing and manipulating data--Series and DataFrame. A Series is similar to a one-dimensional array whereas a DataFrame is a tabular representation akin to a spreadsheet table.

### Series

In [100]:
from pandas import Series

s = Series([3.1, 2.4, -1.7, 0.2, -2.9, 4.5])   # creating a series from a list
print('Series, s =\n', s, '\n')

print(s.values) # display values of the Series
print(s.index) # display indices of the Series
print(s.dtype) # display the element type of the Series
print(s.shape) # get the dimension of the Series
print(s.size) # get the number of elements of the Series
print(s.count()) # get the number of non-null elements of the Series

Series, s =
 0    3.1
1    2.4
2   -1.7
3    0.2
4   -2.9
5    4.5
dtype: float64 

[ 3.1  2.4 -1.7  0.2 -2.9  4.5]
RangeIndex(start=0, stop=6, step=1)
float64
(6,)
6
6


In [102]:
s2 = Series(np.random.randn(6))   # creating a series from a numpy ndarray
print('Series s2 =\n', s2, '\n')

print(s2.values) # display values of the Series
print(s2.index) # display indices of the Series
print(s2.dtypes) # display the element type of the Series

Series s2 =
 0    0.378007
1   -0.365252
2    0.023761
3    0.217282
4    0.496446
5    0.477702
dtype: float64 

[ 0.3780073  -0.36525214  0.02376074  0.21728194  0.49644598  0.47770237]
RangeIndex(start=0, stop=6, step=1)
float64


In [105]:
capitals = {'MI': 'Lansing', 'CA': 'Sacramento', 'TX': 'Austin', 'MN': 'St Paul'}

s4 = Series(capitals)   # creating a series from dictionary object
print('Series s4 =\n', s4, '\n')

print(s4.values) # display values of the Series
print(s4.index) # display indices of the Series
print(s4.dtype) # display the element type of the Series

Series s4 =
 MI       Lansing
CA    Sacramento
TX        Austin
MN       St Paul
dtype: object 

['Lansing' 'Sacramento' 'Austin' 'St Paul']
Index(['MI', 'CA', 'TX', 'MN'], dtype='object')
object


In [111]:
s3 = Series([1.2,2.5,-2.2,3.1,-0.8,-3.2], 
            index = ['Jan 1','Jan 2','Jan 3','Jan 4','Jan 5','Jan 6'])
print('s3 =\n', s3, '\n')

# Accessing elements of a Series
print(s3[2]) # display third element of the Series
print(s3['Jan 4']) # indexing element of a Series 

# display a slice of the Series
print(s3[1:3])
# display a slice of the Series
print(s3.iloc[1:3]) # iloc - integer location

s3 =
 Jan 1    1.2
Jan 2    2.5
Jan 3   -2.2
Jan 4    3.1
Jan 5   -0.8
Jan 6   -3.2
dtype: float64 

-2.2
3.1
Jan 2    2.5
Jan 3   -2.2
dtype: float64
Jan 2    2.5
Jan 3   -2.2
dtype: float64


In [112]:
# applying filter to select non-negative elements of the Series
s3[s3 > 0]

Jan 1    1.2
Jan 2    2.5
Jan 4    3.1
dtype: float64

In [114]:
# Arithmetical operations

print(s3 + 4)
print(s3 / 4)

Jan 1    5.2
Jan 2    6.5
Jan 3    1.8
Jan 4    7.1
Jan 5    3.2
Jan 6    0.8
dtype: float64
Jan 1    0.300
Jan 2    0.625
Jan 3   -0.550
Jan 4    0.775
Jan 5   -0.200
Jan 6   -0.800
dtype: float64


In [116]:
colors = Series(['red', 'blue', 'blue', 'yellow', 'red', 'green', 'blue', np.nan])
print('colors =\n', colors, '\n')

colors.value_counts()

colors =
 0       red
1      blue
2      blue
3    yellow
4       red
5     green
6      blue
7       NaN
dtype: object 



blue      3
red       2
yellow    1
green     1
dtype: int64

### DataFrame

A DataFrame object is a tabular, spreadsheet-like data structure containing a collection of columns, each of which can be of different types (numeric, string, boolean, etc). Unlike Series, a DataFrame has distinct row and column indices. There are many ways to create a DataFrame object (e.g., from a dictionary, list of tuples, or even numpy's ndarrays).

In [119]:
import pandas as pd

cars = {'make': ['Ford', 'Honda', 'Toyota', 'Tesla'],
       'model': ['Taurus', 'Accord', 'Camry', 'Model S'],
       'MSRP': [27595, 23570, 23495, 68000]}          
carData = pd.DataFrame(cars)            # creating DataFrame from dictionary
carData                                 # display the table

make    model   MSRP
0    Ford   Taurus  27595
1   Honda   Accord  23570
2  Toyota    Camry  23495
3   Tesla  Model S  68000

In [121]:
# print the row indices
print(carData.index)
# print the column indices
print(carData.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['make', 'model', 'MSRP'], dtype='object')


In [123]:
# print shape and size 
print(carData.shape)
print(carData.size)

(4, 3)
12


In [126]:
carData2 = DataFrame(cars, index = [1,2,3,4])  # change the row index
carData2['year'] = 2018 # add column with same value
carData2['dealership'] = ['Courtesy Ford', 'Capital Honda', 'Spartan Toyota', 'N/A']
carData2                   # display table

make    model   MSRP  year      dealership
1    Ford   Taurus  27595  2018   Courtesy Ford
2   Honda   Accord  23570  2018   Capital Honda
3  Toyota    Camry  23495  2018  Spartan Toyota
4   Tesla  Model S  68000  2018             N/A

In [128]:
print('Row 3 of car data table:')
carData2.iloc[2]

Row 3 of car data table:


make                  Toyota
model                  Camry
MSRP                   23495
year                    2018
dealership    Spartan Toyota
Name: 3, dtype: object

In [133]:
# accessing a specific element of the DataFrame

print('carData2 =\n', carData2)

print(carData2.iloc[1, 2])  # retrieving second row, third column
print(carData2.loc[1, 'model'])  # retrieving second row, column named 'model'

# accessing a slice of the DataFrame
carData2.iloc[1:3, 1:3]


carData2 =
      make    model   MSRP  year      dealership
1    Ford   Taurus  27595  2018   Courtesy Ford
2   Honda   Accord  23570  2018   Capital Honda
3  Toyota    Camry  23495  2018  Spartan Toyota
4   Tesla  Model S  68000  2018             N/A
23570
Taurus


model   MSRP
2  Accord  23570
3   Camry  23495

In [135]:
# selection and filtering

print('carData2 =\n', carData2, '\n')

print('Where MSRP > 25000')  
carData2[carData2['MSRP'] > 25000]
carData2[carData2.MSRP > 25000]

carData2 =
      make    model   MSRP  year      dealership
1    Ford   Taurus  27595  2018   Courtesy Ford
2   Honda   Accord  23570  2018   Capital Honda
3  Toyota    Camry  23495  2018  Spartan Toyota
4   Tesla  Model S  68000  2018             N/A 

Where MSRP > 25000


make    model   MSRP  year     dealership
1   Ford   Taurus  27595  2018  Courtesy Ford
4  Tesla  Model S  68000  2018            N/A

#### Numpy and Tuple

In [136]:
npdata = np.random.randn(5,3)  # create a 5 by 3 random matrix
columnNames = ['x1','x2','x3']

data = pd.DataFrame(npdata, columns = columnNames)
data

x1        x2        x3
0  0.006995 -1.715498 -1.164648
1  0.417777  1.298030  0.179435
2  0.193238  1.237001 -0.204853
3  0.749008  1.879171  0.071927
4 -0.563086 -0.944774  0.311969

In [137]:
tuplelist = [(2011,45.1,32.4),(2012,42.4,34.5),(2013,47.2,39.2),
              (2014,44.2,31.4),(2015,39.9,29.8),(2016,41.5,36.7)]

columnNames = ['year','temp','precip']
weatherData = DataFrame(tuplelist, columns=columnNames)
weatherData

year  temp  precip
0  2011  45.1    32.4
1  2012  42.4    34.5
2  2013  47.2    39.2
3  2014  44.2    31.4
4  2015  39.9    29.8
5  2016  41.5    36.7

#### Value Count

In [141]:
objects = {'shape': ['circle', 'square', 'square', 'square', 'circle', 'rectangle'],
           'color': ['red', 'red', 'red', 'blue', 'blue', 'blue']}

shapeData = pd.DataFrame(objects)
print('shapeData =\n', shapeData, '\n')

shapeData.value_counts().sort_values(ascending=False)

shapeData =
        shape color
0     circle   red
1     square   red
2     square   red
3     square  blue
4     circle  blue
5  rectangle  blue 



shape      color
square     red      2
circle     blue     1
           red      1
rectangle  blue     1
square     blue     1
dtype: int64

#### Read File

In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\vkx9gmc\\Desktop\\GBS\\Plan for Data Migration\\Hierarchy_python\\Code\\Python Practices\\Work Along'

In [3]:
os.chdir(r"Z:\Performance_Measurement\Team\Hao N\Intro to Python 3\4 Final Project\Work Along - Pokemon")

In [4]:
os.getcwd()

'Z:\\Performance_Measurement\\Team\\Hao N\\Intro to Python 3\\4 Final Project\\Work Along - Pokemon'

In [5]:
# Read CSV file (comma-separated values)
import pandas as pd
csv_pokemon = pd.read_csv('pokemon_data.csv')

In [6]:
csv_pokemon

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [148]:
csv_pokemon.head(3)

#       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45   
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60   
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80   

   Generation  Legendary  
0           1      False  
1           1      False  
2           1      False

In [149]:
csv_pokemon.tail(3)

#                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150   
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170   
799  721            Volcanion     Fire  Water  80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
797      130     70           6       True  
798      130     80           6       True  
799       90     70           6       True

In [153]:
# Read Text file

txt_pokemon = pd.read_csv('pokemon_data.txt', delimiter = '\t')

txt_pokemon 

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [156]:
# Read Excel file

excel_pokemon = pd.read_excel('pokemon_data.xlsx')
excel_pokemon

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

#### Basic syntax

In [157]:
# Statistical Information about the "numerical" data

csv_pokemon.describe()

#          HP      Attack     Defense     Sp. Atk     Sp. Def  \
count  800.000000  800.000000  800.000000  800.000000  800.000000  800.000000   
mean   362.813750   69.258750   79.001250   73.842500   72.820000   71.902500   
std    208.343798   25.534669   32.457366   31.183501   32.722294   27.828916   
min      1.000000    1.000000    5.000000    5.000000   10.000000   20.000000   
25%    184.750000   50.000000   55.000000   50.000000   49.750000   50.000000   
50%    364.500000   65.000000   75.000000   70.000000   65.000000   70.000000   
75%    539.250000   80.000000  100.000000   90.000000   95.000000   90.000000   
max    721.000000  255.000000  190.000000  230.000000  194.000000  230.000000   

            Speed  Generation  
count  800.000000   800.00000  
mean    68.277500     3.32375  
std     29.060474     1.66129  
min      5.000000     1.00000  
25%     45.000000     2.00000  
50%     65.000000     3.00000  
75%     90.000000     5.00000  
max    180.000000     6.00000

In [160]:
# Read each column
csv_pokemon['Type 1']

# Read top 5
csv_pokemon['Type 1'][0:5]

0    Grass
1    Grass
2    Grass
3    Grass
4     Fire
Name: Type 1, dtype: object

In [158]:
# Read header or column name
csv_pokemon.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [161]:
# Read multiple column (doesn't need to be in order)

csv_pokemon[['Name', 'Legendary', 'Attack']]

Name  Legendary  Attack
0                Bulbasaur      False      49
1                  Ivysaur      False      62
2                 Venusaur      False      82
3    VenusaurMega Venusaur      False     100
4               Charmander      False      52
..                     ...        ...     ...
795                Diancie       True     100
796    DiancieMega Diancie       True     160
797    HoopaHoopa Confined       True     110
798     HoopaHoopa Unbound       True     160
799              Volcanion       True     110

[800 rows x 3 columns]

In [162]:
# Read each row (using iloc or integer location)

csv_pokemon.iloc[1]

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [163]:
# Multiple rows
csv_pokemon.iloc[1:4]

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   

   Sp. Def  Speed  Generation  Legendary  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False

In [164]:
# Read a specific location (Row, Column)

csv_pokemon.iloc[2,1]

'Venusaur'

In [166]:
# For Loop to go row by row

for index, row in csv_pokemon.iterrows():
    if (index<5):
        print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander


#### Sorting

In [170]:
# Sorting

csv_pokemon.sort_values('Name') # Alphabetical order A-Z; if it is numerical col, it will order lowest to highest

csv_pokemon.sort_values('Name', ascending = False) # Descending Z-A 

# Get highest HP
csv_pokemon.sort_values(['Type 1', 'HP'], ascending = False)

# Type 1 will be A-Z, and HP will be highest to lowest
csv_pokemon.sort_values(['Type 1', 'HP'], ascending = [1, 0])

#                     Name Type 1    Type 2  HP  Attack  Defense  \
520  469                  Yanmega    Bug    Flying  86      76       86   
698  637                Volcarona    Bug      Fire  85      60       65   
231  214                Heracross    Bug  Fighting  80     125       75   
232  214  HeracrossMega Heracross    Bug  Fighting  80     185      115   
678  617                 Accelgor    Bug       NaN  80      70       40   
..   ...                      ...    ...       ...  ..     ...      ...   
106   98                   Krabby  Water       NaN  30     105       90   
125  116                   Horsea  Water       NaN  30      40       70   
129  120                   Staryu  Water       NaN  30      45       55   
139  129                 Magikarp  Water       NaN  20      10       55   
381  349                   Feebas  Water       NaN  20      15       20   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
520      116       56     95           4      False  
698      135      105    100           5      False  
231       40       95     85           2      False  
232       40      105     75           2      False  
678      100       60    145           5      False  
..       ...      ...    ...         ...        ...  
106       25       25     50           1      False  
125       70       25     60           1      False  
129       70       55     85           1      False  
139       15       20     80           1      False  
381       10       55     80           3      False  

[800 rows x 12 columns]

#### Drop NaNs

In [175]:
csv_pokemon

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [187]:
# csv_pokemon.dropna() # Drop all rows with NA

csv_pokemon.dropna(axis=0) # Drop NAs from a specific column

csv_pokemon.dropna(subset=['Type 2', 'Legendary']) # Drop NAs from mulitple columns

# inplace=True

# csv_pokemon2 = csv_pokemon
# csv_pokemon2.dropna(subset=['Type 2'], inplace=True) 
# csv_pokemon2 

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
6      6              Charizard     Fire  Flying  78      84       78   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
6        109       85    100           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[414 rows x 12 columns]

####  Arithmetic Operations

In [189]:
csv_pokemon['Total'] = csv_pokemon['HP'] +  csv_pokemon['Attack'] + csv_pokemon['Defense'] + csv_pokemon['Sp. Atk'] + csv_pokemon['Sp. Def'] + csv_pokemon['Speed']

In [190]:
csv_pokemon.head(5)

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
6  6              Charizard   Fire  Flying  78      84       78      109   

   Sp. Def  Speed  Generation  Legendary  Total  
0       65     45           1      False    318  
1       80     60           1      False    405  
2      100     80           1      False    525  
3      120     80           1      False    625  
6       85    100           1      False    534

In [191]:
# Drop a column
csv_pokemon = csv_pokemon.drop(columns=['Total'])
csv_pokemon.head(5)

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
6  6              Charizard   Fire  Flying  78      84       78      109   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
6       85    100           1      False

In [7]:
# Second method
csv_pokemon['Total'] = csv_pokemon.iloc[:, 4:10].sum(axis=1) # axis = 1 will sum horizontally
csv_pokemon.head(5)

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  Total  
0       65     45           1      False    318  
1       80     60           1      False    405  
2      100     80           1      False    525  
3      120     80           1      False    625  
4       50     65           1      False    309

#### Rearrange Column

In [9]:
# First method

csv_pokemon[['#', 'Name', 'Type 1', 'Type 2','Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary']]

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [11]:
cols = list(csv_pokemon.columns.values)

In [12]:
cols[-1] # <-- this is a string, so we need to put [] around it to grab the whole column

'Total'

In [14]:
# We want to bring Total column after Type 2

csv_pokemon[cols[0:4] + [cols[-1]] + cols[4:12]]


# Hard-code: be careful of changes in data

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

#### Filtering

In [17]:
# .loc -> filter by conditional

csv_pokemon.loc[csv_pokemon['Type 1'] == 'Fire'].head(5)

#                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
4  4                 Charmander   Fire     NaN  39      52       43       60   
5  5                 Charmeleon   Fire     NaN  58      64       58       80   
6  6                  Charizard   Fire  Flying  78      84       78      109   
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130   
8  6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159   

   Sp. Def  Speed  Generation  Legendary  Total  
4       50     65           1      False    309  
5       65     80           1      False    405  
6       85    100           1      False    534  
7       85    100           1      False    634  
8      115    100           1      False    634

In [19]:
csv_pokemon.loc[(csv_pokemon['Type 1'] == 'Grass') & (csv_pokemon['Type 2'] == 'Poison')]

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Grass  Poison   45      49       49       65   
1      2                Ivysaur  Grass  Poison   60      62       63       80   
2      3               Venusaur  Grass  Poison   80      82       83      100   
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
48    43                 Oddish  Grass  Poison   45      50       55       75   
49    44                  Gloom  Grass  Poison   60      65       70       85   
50    45              Vileplume  Grass  Poison   75      80       85      110   
75    69             Bellsprout  Grass  Poison   50      75       35       70   
76    70             Weepinbell  Grass  Poison   65      90       50       85   
77    71             Victreebel  Grass  Poison   80     105       65      100   
344  315                Roselia  Grass  Poison   50      60       45      100   
451  406                  Budew  Grass  Poison   40      30       35       50   
452  407               Roserade  Grass  Poison   60      70       65      125   
651  590                Foongus  Grass  Poison   69      55       45       55   
652  591              Amoonguss  Grass  Poison  114      85       70       85   

     Sp. Def  Speed  Generation  Legendary  Total  
0         65     45           1      False    318  
1         80     60           1      False    405  
2        100     80           1      False    525  
3        120     80           1      False    625  
48        65     30           1      False    320  
49        75     40           1      False    395  
50        90     50           1      False    490  
75        30     40           1      False    300  
76        45     55           1      False    390  
77        70     70           1      False    490  
344       80     65           3      False    400  
451       70     55           4      False    280  
452      105     90           4      False    515  
651       55     15           5      False    294  
652       80     30           5      False    464

In [20]:
csv_pokemon.loc[(csv_pokemon['Type 1'] == 'Grass') | (csv_pokemon['Type 2'] == 'Poison')]

#                   Name Type 1    Type 2   HP  Attack  Defense  \
0      1              Bulbasaur  Grass    Poison   45      49       49   
1      2                Ivysaur  Grass    Poison   60      62       63   
2      3               Venusaur  Grass    Poison   80      82       83   
3      3  VenusaurMega Venusaur  Grass    Poison   80     100      123   
16    13                 Weedle    Bug    Poison   40      35       30   
..   ...                    ...    ...       ...  ...     ...      ...   
718  650                Chespin  Grass       NaN   56      61       65   
719  651              Quilladin  Grass       NaN   61      78       95   
720  652             Chesnaught  Grass  Fighting   88     107      122   
740  672                 Skiddo  Grass       NaN   66      65       48   
741  673                 Gogoat  Grass       NaN  123     100       62   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total  
0         65       65     45           1      False    318  
1         80       80     60           1      False    405  
2        100      100     80           1      False    525  
3        122      120     80           1      False    625  
16        20       20     50           1      False    195  
..       ...      ...    ...         ...        ...    ...  
718       48       45     38           6      False    313  
719       56       58     57           6      False    405  
720       74       75     64           6      False    530  
740       62       57     52           6      False    350  
741       97       81     68           6      False    531  

[89 rows x 13 columns]

In [21]:
csv_pokemon.loc[(csv_pokemon['Type 1'] == 'Grass') 
               & (csv_pokemon['Type 2'] == 'Poison')
               & (csv_pokemon['HP'] > 70)]

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
2      3               Venusaur  Grass  Poison   80      82       83      100   
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
50    45              Vileplume  Grass  Poison   75      80       85      110   
77    71             Victreebel  Grass  Poison   80     105       65      100   
652  591              Amoonguss  Grass  Poison  114      85       70       85   

     Sp. Def  Speed  Generation  Legendary  Total  
2        100     80           1      False    525  
3        120     80           1      False    625  
50        90     50           1      False    490  
77        70     70           1      False    490  
652       80     30           5      False    464

In [24]:
# Filter string

csv_pokemon.loc[(csv_pokemon['Name'].str.contains('Mega'))]

#                       Name    Type 1    Type 2   HP  Attack  Defense  \
3      3      VenusaurMega Venusaur     Grass    Poison   80     100      123   
7      6  CharizardMega Charizard X      Fire    Dragon   78     130      111   
8      6  CharizardMega Charizard Y      Fire    Flying   78     104       78   
12     9    BlastoiseMega Blastoise     Water       NaN   79     103      120   
19    15      BeedrillMega Beedrill       Bug    Poison   65     150       40   
23    18        PidgeotMega Pidgeot    Normal    Flying   83      80       80   
71    65      AlakazamMega Alakazam   Psychic       NaN   55      50       65   
87    80        SlowbroMega Slowbro     Water   Psychic   95      75      180   
102   94          GengarMega Gengar     Ghost    Poison   60      65       80   
124  115  KangaskhanMega Kangaskhan    Normal       NaN  105     125      100   
137  127          PinsirMega Pinsir       Bug    Flying   65     155      120   
141  130      GyaradosMega Gyarados     Water      Dark   95     155      109   
154  142  AerodactylMega Aerodactyl      Rock    Flying   80     135       85   
163  150        MewtwoMega Mewtwo X   Psychic  Fighting  106     190      100   
164  150        MewtwoMega Mewtwo Y   Psychic       NaN  106     150       70   
168  154                   Meganium     Grass       NaN   80      82      100   
196  181      AmpharosMega Ampharos  Electric    Dragon   90      95      105   
224  208        SteelixMega Steelix     Steel    Ground   75     125      230   
229  212          ScizorMega Scizor       Bug     Steel   70     150      140   
232  214    HeracrossMega Heracross       Bug  Fighting   80     185      115   
248  229      HoundoomMega Houndoom      Dark      Fire   75      90       90   
268  248    TyranitarMega Tyranitar      Rock      Dark  100     164      150   
275  254      SceptileMega Sceptile     Grass    Dragon   70     110       75   
279  257      BlazikenMega Blaziken      Fire  Fighting   80     160       80   
283  260      SwampertMega Swampert     Water    Ground  100     150      110   
306  282    GardevoirMega Gardevoir   Psychic     Fairy   68      85       65   
327  302        SableyeMega Sableye      Dark     Ghost   50      85      125   
329  303          MawileMega Mawile     Steel     Fairy   50     105      125   
333  306          AggronMega Aggron     Steel       NaN   70     140      230   
336  308      MedichamMega Medicham  Fighting   Psychic   60     100       85   
339  310    ManectricMega Manectric  Electric       NaN   70      75       80   
349  319      SharpedoMega Sharpedo     Water      Dark   70     140       70   
354  323      CameruptMega Camerupt      Fire    Ground   70     120      100   
366  334        AltariaMega Altaria    Dragon     Fairy   75     110      110   
387  354        BanetteMega Banette     Ghost       NaN   64     165       75   
393  359            AbsolMega Absol      Dark       NaN   65     150       60   
397  362          GlalieMega Glalie       Ice       NaN   80     120       80   
409  373    SalamenceMega Salamence    Dragon    Flying   95     145      130   
413  376    MetagrossMega Metagross     Steel   Psychic   80     145      150   
418  380          LatiasMega Latias    Dragon   Psychic   80     100      120   
420  381          LatiosMega Latios    Dragon   Psychic   80     130      100   
426  384      RayquazaMega Rayquaza    Dragon    Flying  105     180      100   
476  428        LopunnyMega Lopunny    Normal  Fighting   65     136       94   
494  445      GarchompMega Garchomp    Dragon    Ground  108     170      115   
498  448        LucarioMega Lucario  Fighting     Steel   70     145       88   
511  460    AbomasnowMega Abomasnow     Grass       Ice   90     132      105   
527  475        GalladeMega Gallade   Psychic  Fighting   68     165       95   
591  531          AudinoMega Audino    Normal     Fairy  103      60      126   
796  719        DiancieMega Diancie   

In [25]:
# NOT Contain

csv_pokemon.loc[~(csv_pokemon['Name'].str.contains('Mega'))]

#                 Name   Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1            Bulbasaur    Grass  Poison   45      49       49       65   
1      2              Ivysaur    Grass  Poison   60      62       63       80   
2      3             Venusaur    Grass  Poison   80      82       83      100   
4      4           Charmander     Fire     NaN   39      52       43       60   
5      5           Charmeleon     Fire     NaN   58      64       58       80   
..   ...                  ...      ...     ...  ...     ...      ...      ...   
794  718     Zygarde50% Forme   Dragon  Ground  108     100      121       81   
795  719              Diancie     Rock   Fairy   50     100      150      100   
797  720  HoopaHoopa Confined  Psychic   Ghost   80     110       60      150   
798  720   HoopaHoopa Unbound  Psychic    Dark   80     160       60      170   
799  721            Volcanion     Fire   Water   80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  Total  
0         65     45           1      False    318  
1         80     60           1      False    405  
2        100     80           1      False    525  
4         50     65           1      False    309  
5         65     80           1      False    405  
..       ...    ...         ...        ...    ...  
794       95     95           6       True    600  
795      150     50           6       True    600  
797      130     70           6       True    600  
798      130     80           6       True    680  
799       90     70           6       True    600  

[751 rows x 13 columns]

In [29]:
# Regex Expression
import re

# Get Type 1 = either Grass or Fire

# csv_pokemon.loc[csv_pokemon['Type 1'].str.contains('fire|grass', regex=True)]
# csv_pokemon.loc[csv_pokemon['Type 1'].str.contains('Fire|Grass', regex=True)]

# Ignore cases
csv_pokemon.loc[csv_pokemon['Type 1'].str.contains('fire|grass', flags = re.I , regex=True)]

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Grass  Poison   45      49       49       65   
1      2                Ivysaur  Grass  Poison   60      62       63       80   
2      3               Venusaur  Grass  Poison   80      82       83      100   
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
4      4             Charmander   Fire     NaN   39      52       43       60   
..   ...                    ...    ...     ...  ...     ...      ...      ...   
735  667                 Litleo   Fire  Normal   62      50       58       73   
736  668                 Pyroar   Fire  Normal   86      68       72      109   
740  672                 Skiddo  Grass     NaN   66      65       48       62   
741  673                 Gogoat  Grass     NaN  123     100       62       97   
799  721              Volcanion   Fire   Water   80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  Total  
0         65     45           1      False    318  
1         80     60           1      False    405  
2        100     80           1      False    525  
3        120     80           1      False    625  
4         50     65           1      False    309  
..       ...    ...         ...        ...    ...  
735       54     72           6      False    369  
736       66    106           6      False    507  
740       57     52           6      False    350  
741       81     68           6      False    531  
799       90     70           6       True    600  

[122 rows x 13 columns]

#### Reset Index

In [30]:
new_df = csv_pokemon.loc[(csv_pokemon['Type 1'] == 'Grass') 
               & (csv_pokemon['Type 2'] == 'Poison')
               & (csv_pokemon['HP'] > 70)]
new_df

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
2      3               Venusaur  Grass  Poison   80      82       83      100   
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
50    45              Vileplume  Grass  Poison   75      80       85      110   
77    71             Victreebel  Grass  Poison   80     105       65      100   
652  591              Amoonguss  Grass  Poison  114      85       70       85   

     Sp. Def  Speed  Generation  Legendary  Total  
2        100     80           1      False    525  
3        120     80           1      False    625  
50        90     50           1      False    490  
77        70     70           1      False    490  
652       80     30           5      False    464

In [32]:
# Add index column

new_df.reset_index(drop=True)

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0    3               Venusaur  Grass  Poison   80      82       83      100   
1    3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
2   45              Vileplume  Grass  Poison   75      80       85      110   
3   71             Victreebel  Grass  Poison   80     105       65      100   
4  591              Amoonguss  Grass  Poison  114      85       70       85   

   Sp. Def  Speed  Generation  Legendary  Total  
0      100     80           1      False    525  
1      120     80           1      False    625  
2       90     50           1      False    490  
3       70     70           1      False    490  
4       80     30           5      False    464

In [34]:
# less storing to a memory block

new_df.reset_index(drop=True, inplace = True)

# second method
new_df = new_df.reset_index(drop=True)

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0    3               Venusaur  Grass  Poison   80      82       83      100   
1    3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
2   45              Vileplume  Grass  Poison   75      80       85      110   
3   71             Victreebel  Grass  Poison   80     105       65      100   
4  591              Amoonguss  Grass  Poison  114      85       70       85   

   Sp. Def  Speed  Generation  Legendary  Total  
0      100     80           1      False    525  
1      120     80           1      False    625  
2       90     50           1      False    490  
3       70     70           1      False    490  
4       80     30           5      False    464

#### Conditional Changes

In [35]:
csv_pokemon.loc[csv_pokemon['Type 1'] == 'Grass', 'Type 1'] = 'Leaf'

In [36]:
csv_pokemon

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur     Leaf  Poison  45      49       49   
1      2                Ivysaur     Leaf  Poison  60      62       63   
2      3               Venusaur     Leaf  Poison  80      82       83   
3      3  VenusaurMega Venusaur     Leaf  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total  
0         65       65     45           1      False    318  
1         80       80     60           1      False    405  
2        100      100     80           1      False    525  
3        122      120     80           1      False    625  
4         60       50     65           1      False    309  
..       ...      ...    ...         ...        ...    ...  
795      100      150     50           6       True    600  
796      160      110    110           6       True    700  
797      150      130     70           6       True    600  
798      170      130     80           6       True    680  
799      130       90     70           6       True    600  

[800 rows x 13 columns]

In [37]:
csv_pokemon.loc[csv_pokemon['Total'] > 500 , ['Generation', 'Legendary']] = 'TEST' 

In [38]:
csv_pokemon

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur     Leaf  Poison  45      49       49   
1      2                Ivysaur     Leaf  Poison  60      62       63   
2      3               Venusaur     Leaf  Poison  80      82       83   
3      3  VenusaurMega Venusaur     Leaf  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed Generation Legendary  Total  
0         65       65     45          1     False    318  
1         80       80     60          1     False    405  
2        100      100     80       TEST      TEST    525  
3        122      120     80       TEST      TEST    625  
4         60       50     65          1     False    309  
..       ...      ...    ...        ...       ...    ...  
795      100      150     50       TEST      TEST    600  
796      160      110    110       TEST      TEST    700  
797      150      130     70       TEST      TEST    600  
798      170      130     80       TEST      TEST    680  
799      130       90     70       TEST      TEST    600  

[800 rows x 13 columns]

In [39]:
csv_pokemon.loc[csv_pokemon['Total'] > 500 , ['Generation', 'Legendary']] = ['TEST1', 'TEST2']

In [40]:
csv_pokemon

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur     Leaf  Poison  45      49       49   
1      2                Ivysaur     Leaf  Poison  60      62       63   
2      3               Venusaur     Leaf  Poison  80      82       83   
3      3  VenusaurMega Venusaur     Leaf  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed Generation Legendary  Total  
0         65       65     45          1     False    318  
1         80       80     60          1     False    405  
2        100      100     80      TEST1     TEST2    525  
3        122      120     80      TEST1     TEST2    625  
4         60       50     65          1     False    309  
..       ...      ...    ...        ...       ...    ...  
795      100      150     50      TEST1     TEST2    600  
796      160      110    110      TEST1     TEST2    700  
797      150      130     70      TEST1     TEST2    600  
798      170      130     80      TEST1     TEST2    680  
799      130       90     70      TEST1     TEST2    600  

[800 rows x 13 columns]

#### Groupby

In [47]:
# Which type of Pokemon has the highest average Defense?

csv_pokemon.groupby(['Type 1']).mean().sort_values('Defense', ascending = False)[['Defense']]

Defense
Type 1              
Steel     126.370370
Rock      100.795455
Dragon     86.375000
Ground     84.843750
Ghost      81.187500
Water      72.946429
Ice        71.416667
Leaf       70.800000
Bug        70.724638
Dark       70.225806
Poison     68.821429
Fire       67.769231
Psychic    67.684211
Electric   66.295455
Flying     66.250000
Fighting   65.925926
Fairy      65.705882
Normal     59.846939

In [48]:
csv_pokemon.groupby(['Type 1']).sum()

#    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Total
Type 1                                                                
Bug       23080  3925    4897     4880     3717     4471   4256  26146
Dark      14302  2071    2740     2177     2314     2155   2361  13818
Dragon    15180  2666    3588     2764     3099     2843   2657  17617
Electric  15994  2631    3040     2917     3961     3243   3718  19510
Fairy      7642  1260    1046     1117     1335     1440    826   7024
Fighting   9824  1886    2613     1780     1434     1747   1784  11244
Fire      17025  3635    4408     3524     4627     3755   3871  23820
Flying     2711   283     315      265      377      290    410   1940
Ghost     15568  2062    2361     2598     2539     2447   2059  14066
Ground    11401  2361    3064     2715     1807     2008   2045  14000
Ice       10165  1728    1746     1714     1861     1831   1523  10403
Leaf      24141  4709    5125     4956     5425     4930   4335  29480
Normal    31279  7573    7200     5865     5470     6245   7012  39365
Poison     7050  1883    2091     1927     1692     1803   1780  11176
Psychic   21706  4026    4073     3858     5609     4918   4645  27129
Rock      17280  2876    4086     4435     2787     3321   2460  19965
Steel     11957  1761    2503     3412     1823     2177   1492  13168
Water     33946  8071    8305     8170     8379     7898   7388  48211

In [49]:
csv_pokemon.groupby(['Type 1']).count()

#  Name  Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1                                                                       
Bug        69    69      52   69      69       69       69       69     69   
Dark       31    31      21   31      31       31       31       31     31   
Dragon     32    32      21   32      32       32       32       32     32   
Electric   44    44      17   44      44       44       44       44     44   
Fairy      17    17       2   17      17       17       17       17     17   
Fighting   27    27       7   27      27       27       27       27     27   
Fire       52    52      24   52      52       52       52       52     52   
Flying      4     4       2    4       4        4        4        4      4   
Ghost      32    32      22   32      32       32       32       32     32   
Ground     32    32      19   32      32       32       32       32     32   
Ice        24    24      11   24      24       24       24       24     24   
Leaf       70    70      37   70      70       70       70       70     70   
Normal     98    98      37   98      98       98       98       98     98   
Poison     28    28      13   28      28       28       28       28     28   
Psychic    57    57      19   57      57       57       57       57     57   
Rock       44    44      35   44      44       44       44       44     44   
Steel      27    27      22   27      27       27       27       27     27   
Water     112   112      53  112     112      112      112      112    112   

          Generation  Legendary  Total  
Type 1                                  
Bug               69         69     69  
Dark              31         31     31  
Dragon            32         32     32  
Electric          44         44     44  
Fairy             17         17     17  
Fighting          27         27     27  
Fire              52         52     52  
Flying             4          4      4  
Ghost             32         32     32  
Ground            32         32     32  
Ice               24         24     24  
Leaf              70         70     70  
Normal            98         98     98  
Poison            28         28     28  
Psychic           57         57     57  
Rock              44         44     44  
Steel             27         27     27  
Water            112        112    112

In [50]:
csv_pokemon['count'] = 1

csv_pokemon.groupby(['Type 1']).sum()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Ground       32
Ice          24
Leaf         70
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

In [51]:
csv_pokemon.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2  
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

# Rename Columns

In [52]:
csv_pokemon.rename(columns = {'Sp. Atk': 'Speed Attack', 
                              'Sp. Def' : 'Speed Defense'}, inplace=True)

In [53]:
csv_pokemon

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur     Leaf  Poison  45      49       49   
1      2                Ivysaur     Leaf  Poison  60      62       63   
2      3               Venusaur     Leaf  Poison  80      82       83   
3      3  VenusaurMega Venusaur     Leaf  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Speed Attack  Speed Defense  Speed Generation Legendary  Total  count  
0              65             65     45          1     False    318      1  
1              80             80     60          1     False    405      1  
2             100            100     80      TEST1     TEST2    525      1  
3             122            120     80      TEST1     TEST2    625      1  
4              60             50     65          1     False    309      1  
..            ...            ...    ...        ...       ...    ...    ...  
795           100            150     50      TEST1     TEST2    600      1  
796           160            110    110      TEST1     TEST2    700      1  
797           150            130     70      TEST1     TEST2    600      1  
798           170            130     80      TEST1     TEST2    680      1  
799           130             90     70      TEST1     TEST2    600      1  

[800 rows x 14 columns]

#### Save Data

In [58]:
# csv_pokemon.to_csv('csv_modified.csv', index = False)
# csv_pokemon.to_csv('csv_modified.txt', index = False, sep ='\t')
# csv_pokemon.to_excel('excel_modified.xlsx', index = False)

### Read Multiple files

In [60]:
import glob

path = 'Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data'

filenames = glob.glob(path + "/Sales_*.csv")

all_months_data = pd.DataFrame()

for file in filenames:
    print(file)
    current_data = pd.read_csv(file)
    all_months_data = pd.concat([all_months_data, current_data])

print('Done')


Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data\Sales_April_2019.csv
Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data\Sales_August_2019.csv
Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data\Sales_December_2019.csv
Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data\Sales_February_2019.csv
Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data\Sales_January_2019.csv
Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data\Sales_July_2019.csv
Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data\Sales_June_2019.csv
Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Data\Sales_March_2019.csv
Z:/Performance_Measurement/Team/Hao N/Intro to Python 3/4 Final Project/Example - Sale Da

In [61]:
all_months_data

Order ID                     Product Quantity Ordered Price Each  \
0       176558        USB-C Charging Cable                2      11.95   
1          NaN                         NaN              NaN        NaN   
2       176559  Bose SoundSport Headphones                1      99.99   
3       176560                Google Phone                1        600   
4       176560            Wired Headphones                1      11.99   
...        ...                         ...              ...        ...   
11681   259353      AAA Batteries (4-pack)                3       2.99   
11682   259354                      iPhone                1        700   
11683   259355                      iPhone                1        700   
11684   259356      34in Ultrawide Monitor                1     379.99   
11685   259357        USB-C Charging Cable                1      11.95   

           Order Date                         Purchase Address  
0      04/19/19 08:46             917 1st St, Dallas, TX 75001  
1                 NaN                                      NaN  
2      04/07/19 22:30        682 Chestnut St, Boston, MA 02215  
3      04/12/19 14:38     669 Spruce St, Los Angeles, CA 90001  
4      04/12/19 14:38     669 Spruce St, Los Angeles, CA 90001  
...               ...                                      ...  
11681  09/17/19 20:56   840 Highland St, Los Angeles, CA 90001  
11682  09/01/19 16:00  216 Dogwood St, San Francisco, CA 94016  
11683  09/23/19 07:39     220 12th St, San Francisco, CA 94016  
11684  09/19/19 17:30   511 Forest St, San Francisco, CA 94016  
11685  09/30/19 00:18   250 Meadow St, San Francisco, CA 94016  

[186850 rows x 6 columns]